resources:
  - clusterrole.yaml
  - clusterrole_maas_configs.yaml
  - clusterrolebinding_maas_configs.yaml
  - clusterrole_binding.yaml
  - service_account.yaml
  - leader_election_role.yaml
  - leader_election_role_binding.yaml
  - secret_migrate_role_controller.yaml
  - secret_migrate_role_infra.yaml
  - secret_migrate_rolebinding_controller.yaml
  - secret_migrate_rolebinding_infra.yaml
  - owner_role.yaml
  - viewer_role.yaml
