apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-migrate-rolebinding-controller
  namespace: opendatahub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-migrate-role-controller
subjects:
- kind: ServiceAccount
  name: maas-controller
  namespace: opendatahub
