apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-migrate-rolebinding-infra
  namespace: odh-ai-gateway-infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-migrate-role-infra
subjects:
- kind: ServiceAccount
  name: maas-controller
  namespace: opendatahub
